application: stoked-depth-92800
version: 1
runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /.*
  script: pictures_comments.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
# [END libraries]
